### PR TITLE
feat(svg): add svg url export to compatible with umi

### PR DESCRIPTION
**Pull request by kuitos**
使用 `import { ReactComponent as SvgC } from './c.svg'` 的方式导出 react component，兼容 umi 的处理及 docz 的 svgr 插件 https://github.com/doczjs/docz/blob/1ac1ea8/packages/docz-plugin-svgr/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/umijs/father/117)

### CODE REVIEW

**Comment by sorrycc** [comment]
ci 挂是这个 PR 引入的，https://github.com/rollup/rollup-plugin-url/blob/master/package.json#L49

**Comment by kuitos** [comment]
给 rollup-plugin-url 提了个 pr https://github.com/rollup/rollup-plugin-url/pull/24

**Comment by kuitos** [comment]
@sorrycc ci passed

**Comment by sorrycc** [comment]
+ father-build@1.12.0
+ father@2.22.0

**Pull request merged**
